feat: Added JWT Encoding / Decoding functionality
supertokens/jwt-decoder pull request #2
Opened 2023-01-30 09:14 UTC by AreebKhan619

2023-02-07 09:08 UTC, nkshah2 requested changes

2023-02-07 09:08 UTC, nkshah2 commented on app/assets/images/index.ts
> +import StructureOfJwt from "./structure-of-jwt.png"
This asset is really large, is the image size the same as the usage size? If yes that whats the display size? Either way ~400kb is massive and we should find a way to reduce it

2023-02-07 09:08 UTC, nkshah2 commented on app/assets/constants.ts
> +  requiresBothKeys?: boolean;
a better boolean would be `isSymmetricKey` or something similar but you can leave it as is

2023-02-07 09:08 UTC, nkshah2 commented on .babelrc
> -{
Remove the empty README files

2023-02-07 09:08 UTC, nkshah2 commented on .babelrc
> -{
Also if we dont need a circleci job for this then delete the config file. Otherwise pushes will still trigger circleci jobs that will fail

2023-02-07 09:09 UTC, nkshah2 commented
@makerboiAdi @jscyo Is the route `/jwt-decoder` confirmed? (supertokens.com/jwt-decoder). @AreebKhan619 Make sure to change the path everywhere if it needs to be changed

2023-02-07 09:10 UTC, nkshah2 commented
@mufassirkazi How will the SEO for this work? Meta tags, og image etc will need to be added for this tool. Also do we need any analytics for this?

2023-02-07 12:59 UTC, mufassirkazi commented
@nkshah2 

Yes there will be analytics for this (will give). SEO-wise, I'll provide the OG image, title meta and meta descp. Will get advait to look at it. 

@AreebKhan619 can you please demo through this with me?

2023-02-20 08:10 UTC, nkshah2 requested changes

2023-02-20 08:10 UTC, nkshah2 commented on app/pages/_app.tsx
> +import React from "react"
On mobile version you cant see the content for the info icon (looks like its only set to show on hover but mobile would need it to show on click as well)

https://user-images.githubusercontent.com/18233774/220048331-c5d7f32e-75ff-4c8d-b70d-972ba8ed3c7a.mov

2023-02-20 08:10 UTC, nkshah2 commented on app/pages/_app.tsx
> +import Theme from "../assets/global-styles/theme"
In the mobile version, the bullet titles wrap strangely. Making it look like something is broken

![Screenshot 2023-02-20 at 1 36 22 PM](https://user-images.githubusercontent.com/18233774/220048527-77f770e7-7d32-44f5-8267-3493e957171b.png)

2023-02-27 06:31 UTC, nkshah2 approved these changes

2023-02-27 06:31 UTC, merged